# Generated by Django 3.1.8 on 2021-04-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_pick_up', models.CharField(max_length=50)),
                ('date_of_pick_up', models.CharField(max_length=50)),
                ('address_of_pick_up', models.CharField(max_length=50)),
            ],
        ),
    ]
